# ============================================
# Grafana 自动配置: Prometheus 数据源
# ============================================

apiVersion: 1

datasources:
  - name: Prometheus-van-ea
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 30s
      tlsSkipVerify: true
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.54.0
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
    secureJsonData: {}
